<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Primary module hooks for liac module.
 */


/**
 * Implements hook_theme().
 */
function liac_theme()
{
    return [
    'liac_footer_block' => [
      'variables' => [
        'data' => null,
      ],
      'template' => 'liac-footer-block',
    ],
    ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function liac_form_contact_message_feedback_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
    $form['subject']['widget'][0]['value']['#title'] = t('Θέμα');
    $form['message']['widget'][0]['value']['#title'] = t('Κείμενο');
    $form['name']['#title'] = t('Ονοματεπώνυμο');
    $form['mail']['#title'] = t('Email');
    $form['actions']['submit']['#value'] = t('Αποστολή');
    $form['actions']['preview']['#access'] = FALSE;

  }

