<?php

use Drupal\node\Entity\Node;

/**
 * @file
 * Theme and preprocess functions for blocks.
 */


 /**
 * Implements hook_preprocess_block().
 */
// function lia_preprocess_block__lia_page_title(&$variables) {

//   //Get current page
//   $current_page = \Drupal::routeMatch()->getParameter('node');
//   if ($current_page instanceof Node && $current_page->getType() === 'page') {
//     dpm('I AM IN ');
//     dpm($variables);
//      $variables['elements']['content']['#region'] = 'header';
//   }
// }
